name: time_trial
description: A sample command-line application.
version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: '>=2.18.2 <3.0.0'

# dependencies:
#   path: ^1.8.0

dev_dependencies:
  lints: ^2.0.0
  
dependencies:
  test: ^1.22.1
  async: ^2.8.2
  date_format: ^2.0.6
  intl: ^0.17.0
  bloc: ^8.1.0
  alarmclock: ^0.0.2
  fake_async: ^1.3.1
  
  
